name: release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - run: python build.py
      - uses: actions/upload-artifact@v4
        with:
          name: ppixiv.user.js
          path: output/ppixiv-main.user.js

